/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVaccinationsRouteImport } from './routes/_authenticated/vaccinations'
import { Route as AuthenticatedConsultPatientIdRouteImport } from './routes/_authenticated/consult.$patientId'
import { Route as AuthenticatedPrescriptionConsultIdRouteImport } from './routes/_authenticated/prescription.$consultId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaccinationsRoute =
  AuthenticatedVaccinationsRouteImport.update({
    id: '/vaccinations',
    path: '/vaccinations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultPatientIdRoute =
  AuthenticatedConsultPatientIdRouteImport.update({
    id: '/consult/$patientId',
    path: '/consult/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrescriptionConsultIdRoute =
  AuthenticatedPrescriptionConsultIdRouteImport.update({
    id: '/prescription/$consultId',
    path: '/prescription/$consultId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/consult/$patientId': typeof AuthenticatedConsultPatientIdRoute
  '/prescription/$consultId': typeof AuthenticatedPrescriptionConsultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/consult/$patientId': typeof AuthenticatedConsultPatientIdRoute
  '/prescription/$consultId': typeof AuthenticatedPrescriptionConsultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vaccinations': typeof AuthenticatedVaccinationsRoute
  '/_authenticated/consult/$patientId': typeof AuthenticatedConsultPatientIdRoute
  '/_authenticated/prescription/$consultId': typeof AuthenticatedPrescriptionConsultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/vaccinations'
    | '/consult/$patientId'
    | '/prescription/$consultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/vaccinations'
    | '/consult/$patientId'
    | '/prescription/$consultId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/vaccinations'
    | '/_authenticated/consult/$patientId'
    | '/_authenticated/prescription/$consultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vaccinations': {
      id: '/_authenticated/vaccinations'
      path: '/vaccinations'
      fullPath: '/vaccinations'
      preLoaderRoute: typeof AuthenticatedVaccinationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consult/$patientId': {
      id: '/_authenticated/consult/$patientId'
      path: '/consult/$patientId'
      fullPath: '/consult/$patientId'
      preLoaderRoute: typeof AuthenticatedConsultPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescription/$consultId': {
      id: '/_authenticated/prescription/$consultId'
      path: '/prescription/$consultId'
      fullPath: '/prescription/$consultId'
      preLoaderRoute: typeof AuthenticatedPrescriptionConsultIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVaccinationsRoute: typeof AuthenticatedVaccinationsRoute
  AuthenticatedConsultPatientIdRoute: typeof AuthenticatedConsultPatientIdRoute
  AuthenticatedPrescriptionConsultIdRoute: typeof AuthenticatedPrescriptionConsultIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVaccinationsRoute: AuthenticatedVaccinationsRoute,
  AuthenticatedConsultPatientIdRoute: AuthenticatedConsultPatientIdRoute,
  AuthenticatedPrescriptionConsultIdRoute:
    AuthenticatedPrescriptionConsultIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
